# NumPy: The Fundamental Package for Scientific Computing

## What is NumPy?
**NumPy (Numerical Python)** is a core library for numerical computing in Python.  
It provides a powerful **N-dimensional array object** and tools for working with these arrays.

---

## Basic Definition
```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])  # Creates a NumPy array
```
## Why NumPy when Python Lists Exist?

- **Performance:** NumPy arrays are **10–100x faster** than Python lists.  
- **Memory Efficiency:** Stores data more compactly.  
- **Vectorized Operations:** Enables **element-wise operations** without loops.  
- **Rich Functionality:** Includes built-in **mathematical** and **linear algebra** operations.  

---

## Vectorization & SIMD

NumPy uses **vectorization** through **SIMD (Single Instruction, Multiple Data)** operations.

### Example
```python
# Traditional Python (slow)
result = [x + y for x, y in zip(list1, list2)]

# NumPy vectorized (fast - uses SIMD)
result = arr1 + arr2  # Single operation on entire arrays
```
### SIMD Advantage
Processes multiple data elements **simultaneously** using the CPU’s **parallel processing** capabilities,  
instead of sequential element-by-element computation.

---

## Purpose of NumPy

- **Scientific computing** and **data analysis**  
- **Machine learning** and **AI**  
- **Image processing**  
- **Financial modeling**  
- Any computation requiring **high-performance numerical operations**

> **Note:** NumPy forms the **foundation** for the entire Python data science ecosystem — including **Pandas**, **SciPy**, and **Scikit-learn**.



# NumPy Array Attributes

## Core Attributes

### Shape & Dimensions
- **`ndim`** → Number of dimensions in the array  
- **`shape`** → Tuple representing array dimensions  
- **`size`** → Total number of elements in the array  

```python
import numpy as np
arr = np.array([[1,2,3], [4, 5, 6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
```
---

### Data Type & Memory
- **`dtype`** → Data type of array elements (e.g., `int64`, `float64`)  
- **`itemsize`** → Memory (in bytes) per element  
- **`nbytes`** → Total memory consumed by the array  

```python
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
```
---

### Array Content
- **`data`** → Buffer containing the actual array elements  
- **`T`** → Transposed version of the array (swaps rows and columns)  

```python
print(arr.data)
print(arr.T)
```
---


In [8]:
import numpy as np

# Function to display array info neatly
def display_array_info(arr, name):
    print(f"* {name} Info")
    print(f"Dimension   = {arr.ndim}")
    print(f"Shape       = {arr.shape}")
    print(f"Size        = {arr.size}")
    print(f"Data Type   = {arr.dtype}")
    print(f"Item Size   = {arr.itemsize} bytes")
    print(f"Total Bytes = {arr.nbytes}")
    print("-" * 50)

# 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
display_array_info(arr, "1D Array")

# 2D array
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
display_array_info(arr1, "2D Array")

# 3D array
arr2 = np.array([
    [[1, 2, 3],
     [4, 5, 6],
    ],

    [[7, 8, 9],
     [10, 11, 12]],
    
    [[13, 14, 15],
     [16, 17, 18]]
])
display_array_info(arr2, "3D Array")


* 1D Array Info
Dimension   = 1
Shape       = (6,)
Size        = 6
Data Type   = int64
Item Size   = 8 bytes
Total Bytes = 48
--------------------------------------------------
* 2D Array Info
Dimension   = 2
Shape       = (4, 3)
Size        = 12
Data Type   = int64
Item Size   = 8 bytes
Total Bytes = 96
--------------------------------------------------
* 3D Array Info
Dimension   = 3
Shape       = (3, 2, 3)
Size        = 18
Data Type   = int64
Item Size   = 8 bytes
Total Bytes = 144
--------------------------------------------------


# NumPy Data Type Casting

## Upcasting (Automatic Promotion)

**Definition:**  
Automatic promotion to a more general or compatible data type when arrays with different `dtypes` are combined.

---

### 🔼 Upcasting Hierarchy
`bool → int8 → int16 → int32 → int64 → float32 → float64 → complex64 → complex128`


### ✳️ Examples of Upcasting
- **Integer to Float:**  
  When an integer array is combined with a float array, NumPy automatically promotes the result to `float64`.
```python
import numpy as np
# Integer to Float
int_arr = np.array([1, 2, 3])        # dtype: int64
float_arr = np.array([1.5, 2.5])     # dtype: float64
result = int_arr + float_arr          # dtype: float64
```
- **Mixed Types (Bool + Int):**  
  Combining a boolean array with an integer array results in an `int64` array, since `int` is higher in hierarchy than `bool`.
```python
import numpy as np
# Mixed types
bool_arr = np.array([True, False])   # dtype: bool
int_arr = np.array([1, 2])           # dtype: int64
result = bool_arr + int_arr          # dtype: int64
```
---

## String Upcasting (Highest in Hierarchy)

- Strings **dominate all other data types** during casting.  
- Combining numbers and strings converts all elements to **Unicode string** type (`<U...`).

> ⚠️ Note: Direct addition between numeric and string arrays raises an **error**, but NumPy will automatically assign a **string dtype** if such mixed values exist in a single array.

Example result:
```python
# String dominates all other types
int_arr = np.array([1, 2, 3])
str_arr = np.array(['a', 'b'])
result = int_arr + str_arr           # ERROR! But if combined:
mixed = np.array([1, 'hello'])       # dtype: <U5 (string)
```

---

## Downcasting (Explicit Demotion)

**Definition:**  
Manual conversion of a higher or larger data type to a smaller or specific one using `astype()`.

### 🧮 Common Examples
- **Float → Integer:**  
  Converts and **truncates decimals** (not rounding).  
```python
import numpy as np
    # Float to Integer (truncates decimal)
    float_arr = np.array([1.7, 2.3, 3.9])
    int_arr = float_arr.astype(np.int32)  # [1, 2, 3]
```

- **Larger → Smaller Integer:**  
  Casting `int64` to `int16` may cause **overflow** if values exceed the smaller type’s range.
```python
import numpy as np
# Larger to smaller integer
int64_arr = np.array([100, 200], dtype=np.int64)
int16_arr = int64_arr.astype(np.int16)  # Potential overflow risk!
```

> ⚠️ Note: Downcasting should be done carefully to avoid **data loss** or **overflow errors**.

---

## Selecting Specific Data Types

### ✳️ Explicit Declaration During Creation
You can specify a data type while creating an array using the `dtype` parameter.

Examples:
- `dtype=np.float32`
- `dtype=np.int16`
- `dtype=np.complex64`

Or use **type codes**:
- `'f4'` → float32  
- `'i2'` → int16  

```python
import numpy as np
# During creation
arr1 = np.array([1, 2, 3], dtype=np.float32)
arr2 = np.array([1, 2, 3], dtype=np.int16)
arr3 = np.array([1, 2, 3], dtype=np.complex64)

# Using type codes
arr4 = np.array([1, 2, 3], dtype='f4')  # float32
arr5 = np.array([1, 2, 3], dtype='i2')  # int16
```
---

## Common Data Types in NumPy

| Category | Data Types | Description |
|-----------|-------------|-------------|
| **Integers** | `np.int8`, `np.int16`, `np.int32`, `np.int64` | Signed integers |
| **Floats** | `np.float16`, `np.float32`, `np.float64` | Floating-point numbers |
| **Complex** | `np.complex64`, `np.complex128` | Complex numbers |
| **Boolean** | `np.bool_` | True/False values |
| **Object** | `np.object_` | Arbitrary Python objects |
| **Strings** | `np.string_`, `np.unicode_` | Fixed-length string data |

---

> 💡 **Note:**  
> - NumPy promotes types automatically (**upcasting**) to avoid precision loss.  
> - Use `astype()` for manual type conversion (**downcasting**) when optimization or specific data handling is required.  
> - Always check `arr.dtype` before performing numerical operations to ensure expected behavior.



In [15]:
# Upcasting
import numpy as np
int_arr = np.array([1, 2, 3])
float_arr = np.array([1.2, 2.3, 3.4])
mixed = int_arr + float_arr
int_bool = np.array([1,2,True, False])
string_int_float_bool = np.array([1, 2, "hello", 2.5, True, 3.5])
print(mixed.dtype) # float_64
print(int_bool.dtype) # int_64
print(string_int_float_bool.dtype) # <U32
print("-"*20)


# Downcasting

float_arr = np.array([1.2, 3.4, 5.6, 6.7])
int_ar = float_arr.astype(np.int32)
print(int_ar.dtype)
print("-"*20)

# Selecting a specific data type
spec_float_arr = np.array([1, 2, 3, 4], dtype = np.float32)
print(spec_float_arr.dtype)
spec_int_arr = np.array([2, 3, 4, 5], dtype = np.int16)
print(spec_int_arr.dtype)

float64
int64
<U32
--------------------
int32
--------------------
float32
int16


# Special Notes: ndarray Creation from Python Data Structures

##  Set → ndarray
**Must convert the set to a list first.**  
Directly passing a set to `np.array()` can give **unpredictable results** because sets are **unordered collections**. Also sets are saved as object in the ndarray, so casting to a specific data type isn't possible.

**Why?**  
Sets do not preserve element order, so each run may produce a different arrangement.  
Correct approach: Convert the set to a list before creating the array.

---

##  Dictionary → ndarray

### Keys & Values
To convert dictionary data into arrays:
- Use `list(dict.keys())` for keys  
- Use `list(dict.values())` for values  

**Note:** `.keys()` and `.values()` return **view objects**, not lists — so you must convert them first.

### Items (Key-Value Pairs)
Using `list(dict.items())` creates a **2D array** of key–value pairs.  
However, since keys are **strings** and values are **integers**, NumPy automatically **upcasts** all elements to **strings**.

**Warning:** Mixed types (e.g., string + int) will be promoted to a **common dtype (`<U...`)**, making the array non-numeric.

---

## Tuple vs List
Both **tuples** and **lists** behave **identically** when used to create NumPy arrays.  
The resulting array will have the same structure and data type.

> Use either — no functional difference in ndarray creation.

---

## Nested Structures
When nested lists or tuples have **unequal lengths**, NumPy cannot form a proper multi-dimensional numeric array.  
Instead, it creates an **object array**, where each element is treated as a generic Python object.

**Irregular shapes = Object arrays**, not numerical ndarrays.

> Example: `[[1, 2], [3, 4, 5]]` results in an array of dtype `object`.

---

## Mixed Data Types
Arrays containing elements of **different data types** automatically **upcast** to the most general compatible type.  
If strings are present, they **dominate** all others — converting the entire array to a string type (`<U...`).

> Example: `[1, "hello", 3.14] → ['1' 'hello' '3.14'] (dtype='<U32')`

---

### Summary
| Python Structure | Works Directly | Special Handling Needed | Notes |
|------------------|----------------|--------------------------|-------|
| **List / Tuple** |  Yes |  No | Behave identically |
| **Set** |  No |  Convert to list | Sets are unordered |
| **Dictionary** |  Partial |  Convert keys/values/items to list | Mixed types upcast to strings |
| **Nested (Irregular)** |  No |  Ensure equal lengths | Otherwise creates object array |
| **Mixed Data Types** | Yes |  Auto upcast | Strings dominate all |

---

> **Key Takeaway:**  
> Always ensure **consistent data types** and **regular shapes** when creating NumPy arrays from Python structures.  
> Irregular or mixed data leads to **object arrays** or **string upcasting**, which may limit numerical operations.


In [20]:
import numpy as np

# 1. From List
print("=== From List ===")
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print(f"List: {list_data} -> Array: {arr_from_list}")


# 2. From Tuple
print("\n=== From Tuple ===")
tuple_data = (6, 7, 8, 9, 10)
arr_from_tuple = np.array(tuple_data)
print(f"Tuple: {tuple_data} -> Array: {arr_from_tuple}")
print("-"*50)

# 3. From Set
print("\n=== From Set ===")
set_data = {1, 2, 3, 2, 1}  # Duplicates removed
arr_from_set = np.array(list(set_data))  # Convert to list first
print(f"Set: {set_data} -> Array: {arr_from_set}")
print("-"*50)

# 4. From Dictionary
print("\n=== From Dictionary ===")
dict_data = {'a': 1, 'b': 2, 'c': 3}
print("-"*50)

# 4.1 From Dictionary KEYS
arr_from_dict_keys = np.array(list(dict_data.keys()))
print(f"Dict Keys: {dict_data.keys()} -> Array: {arr_from_dict_keys}")
print("-"*50)

# 4.2 From Dictionary VALUES
arr_from_dict_values = np.array(list(dict_data.values()))
print(f"Dict Values: {dict_data.values()} -> Array: {arr_from_dict_values}")
print("-"*50)

# 4.3 From Dictionary ITEMS --> 2D array
arr_from_dict_items = np.array(list(dict_data.items()))
print(f"Dict Items: {dict_data.items()} -> Array: {arr_from_dict_items}")
print("-"*50)

# 5. 2D Arrays from Nested Structures
print("\n=== 2D Arrays ===")
nested_list = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(nested_list)
print(f"Nested List: {nested_list}")
print(f"2D Array:\n{arr_2d}")
print(f"Shape: {arr_2d.shape}")
print("-"*50)

# 6. Specifying Data Type
print("\n=== With Specific Data Type ===")
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(f"List: [1, 2, 3] -> Float Array: {arr_float} dtype: {arr_float.dtype}")
print("-"*50)

# 7. Mixed Data Types (Upcasting)
print("\n=== Mixed Data Types ===")
mixed_data = [1, 2.5, 3]  # Int and Float
arr_mixed = np.array(mixed_data)
print(f"Mixed: {mixed_data} -> Array: {arr_mixed} dtype: {arr_mixed.dtype}")

=== From List ===
List: [1, 2, 3, 4, 5] -> Array: [1 2 3 4 5]

=== From Tuple ===
Tuple: (6, 7, 8, 9, 10) -> Array: [ 6  7  8  9 10]
--------------------------------------------------

=== From Set ===
Set: {1, 2, 3} -> Array: [1 2 3]
--------------------------------------------------

=== From Dictionary ===
--------------------------------------------------
Dict Keys: dict_keys(['a', 'b', 'c']) -> Array: ['a' 'b' 'c']
--------------------------------------------------
Dict Values: dict_values([1, 2, 3]) -> Array: [1 2 3]
--------------------------------------------------
Dict Items: dict_items([('a', 1), ('b', 2), ('c', 3)]) -> Array: [['a' '1']
 ['b' '2']
 ['c' '3']]
--------------------------------------------------

=== 2D Arrays ===
Nested List: [[1, 2, 3], [4, 5, 6]]
2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
--------------------------------------------------

=== With Specific Data Type ===
List: [1, 2, 3] -> Float Array: [1. 2. 3.] dtype: float32
------------------------------

# NumPy Array Creation Functions with Modifiable Parameters

NumPy provides several convenient functions for creating arrays initialized with specific values or patterns.  
These functions simplify array generation for numerical and scientific computing.

---

## 🔹 1. `np.zeros(shape, dtype=float)`
**Parameters:**  
- `shape` → Shape of the array (int or tuple)  
- `dtype` → Data type of elements (default: float)  
**Explanation:** Creates an array filled with zeros.

---

## 🔹 2. `np.zeros_like(a, dtype=None, shape=None)`
**Parameters:**  
- `a` → Template array  
- `dtype` → Overrides dtype of output array  
- `shape` → Overrides shape  
**Explanation:** Creates a zero array matching the shape and type of `a`.

---

## 🔹 3. `np.ones(shape, dtype=float)`
**Parameters:** Same as `np.zeros()`  
**Explanation:** Creates an array filled with ones.

---

## 🔹 4. `np.ones_like(a, dtype=None, shape=None)`
**Parameters:** Same as `np.zeros_like()`  
**Explanation:** Creates an array of ones with the same structure as another array.

---

## 🔹 5. `np.empty(shape, dtype=float)`
**Parameters:** Same as `np.zeros()`  
**Explanation:** Creates an uninitialized array with arbitrary values (for performance).

---

## 🔹 6. `np.full(shape, fill_value, dtype=None)`
**Parameters:**  
- `shape` → Shape of the array  
- `fill_value` → Value to fill  
- `dtype` → Data type (optional)  
**Explanation:** Creates an array filled with a specific value.

---

## 🔹 7. `np.full_like(a, fill_value, dtype=None, shape=None)`
**Parameters:** Same as `np.zeros_like()` with `fill_value`  
**Explanation:** Creates an array filled with a value, matching another array's shape and type.

---

## 🔹 8. Special Values
- `np.inf` → Infinity  
- `-np.inf` → Negative infinity  
- `np.nan` → Not a Number (NaN)  
**Explanation:** Useful for mathematical modeling and handling undefined values.

---

## 🔹 9. Mixed Data Types
- Boolean arrays (`True`/`False`)  
- Complex arrays (`a + bj`)  
**Explanation:** Create arrays with specific types for logical or complex computations.

---

## 🔹 10. Quick Comparison
| Function | Modifiable Parameters | One-line Explanation |
|-----------|--------------------|--------------------|
| `np.zeros()` | `shape, dtype` | Creates an array of zeros |
| `np.ones()` | `shape, dtype` | Creates an array of ones |
| `np.empty()` | `shape, dtype` | Creates an uninitialized array |
| `np.full()` | `shape, fill_value, dtype` | Creates an array filled with a specific value |

---

### Key Takeaways
- `zeros()` and `ones()` → Quick initialization  
- `empty()` → High-performance, uninitialized arrays  
- `full()` and variants → Arrays with custom fill values  
- `*_like()` → Create arrays matching another array’s structure and dtype

import numpy as np

print("=== NUMPY ARRAY CREATION FUNCTIONS ===\n")

template = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Template:\n{template}")
print("-"*50)

# 1. Zeros
print("1. ZERO ARRAYS")
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((2, 3))
zeros_int = np.zeros(4, dtype=np.int32)
print(f"np.zeros(5): {zeros_1d}")
print(f"np.zeros((2,3)):\n{zeros_2d}")
print(f"np.zeros(4, dtype=int): {zeros_int}")
print("-"*50)

# 2. Zeros Like
print("\n2. ZEROS LIKE")
zeros_like = np.zeros_like(template)
print(f"np.zeros_like(template):\n{zeros_like}")
print("-"*50)

# 3. Ones
print("\n3. ONE ARRAYS")
ones_1d = np.ones(4)
ones_2d = np.ones((3, 2))
ones_float = np.ones(3, dtype=np.float32)
print(f"np.ones(4): {ones_1d}")
print(f"np.ones((3,2)):\n{ones_2d}")
print(f"np.ones(3, dtype=float32): {ones_float}")
print("-"*50)

# 4. Ones Like
print("\n4. ONES LIKE")
ones_like = np.ones_like(template)
print(f"np.ones_like(template):\n{ones_like}")
print("-"*50)

# 5. Empty
print("\n5. EMPTY ARRAYS")
empty_arr = np.empty((2, 2))
print(f"np.empty((2,2)):\n{empty_arr}")  # Contains garbage values
print("-"*50)

# 6. Full
print("\n6. FULL ARRAYS")
full_1d = np.full(5, 7)
full_2d = np.full((2, 3), 2.5)
full_str = np.full(3, "hello")
print(f"np.full(5, 7): {full_1d}")
print(f"np.full((2,3), 2.5):\n{full_2d}")
print(f"np.full(3, 'hello'): {full_str}")
print("-"*50)

# 7. Full Like
print("\n7. FULL LIKE")
full_like = np.full_like(template, 99)
full_like_float = np.full_like(template, 3.14)
print(f"np.full_like(template, 99):\n{full_like}")
print(f"np.full_like(template, 3.14):\n{full_like_float}")
print("-"*50)

# 8. Special Values
print("\n8. SPECIAL VALUES")
inf_arr = np.full(3, np.inf)
nan_arr = np.full(4, np.nan)
neg_inf = np.full(2, -np.inf)
print(f"Infinity array: {inf_arr}")
print(f"NaN array: {nan_arr}")
print(f"Negative infinity: {neg_inf}")
print("-"*50)

# 9. Mixed Examples
print("\n9. MIXED EXAMPLES")
# Creating with different dtypes
arr_bool = np.full((2, 2), True)
arr_complex = np.full(3, 2+3j)
print(f"Boolean full: {arr_bool}")
print(f"Complex full: {arr_complex}")
print("-"*50)

# 10. Quick Comparison
print("\n10. QUICK COMPARISON")
shape = (2, 2)
print(f"Shape: {shape}")
print(f"Zeros:\n{np.zeros(shape)}")
print(f"Ones:\n{np.ones(shape)}")
print(f"Empty:\n{np.empty(shape)}")  # Random values
print(f"Full(5):\n{np.full(shape, 5)}")
print("-"*50)


# Most Used NumPy Random Functions

NumPy provides versatile random functions for generating numbers, sampling, and simulations. These are widely used in data analysis, machine learning, statistical modeling, and testing algorithms.

---

## 🔹 1. `np.random.randint(low, high=None, size=None)`
- **Parameters:**  
  - `low` → Minimum integer (inclusive)  
  - `high` → Maximum integer (exclusive)  
  - `size` → Output shape  
- **Description:** Generates random integers in a given range. Can create 1D or multi-dimensional arrays.  
- **Example Use:** Dice rolls, random labels, discrete simulations.

---

## 🔹 2. `np.random.rand(d0, d1, ..., dn)`
- **Parameters:**  
  - `d0, d1, ..., dn` → Dimensions of the output array  
- **Description:** Generates **uniform random numbers** in `[0, 1)`.  
- **Example Use:** Normalized random datasets, random initialization.

---

## 🔹 3. `np.random.uniform(low=0.0, high=1.0, size=None)`
- **Parameters:**  
  - `low` → Lower bound  
  - `high` → Upper bound  
  - `size` → Output shape  
- **Description:** Generates uniform random numbers in a **custom range** `[low, high)`.  
- **Example Use:** Custom-range simulations, synthetic datasets.

---

## 🔹 4. `np.random.randn(d0, d1, ..., dn)`
- **Parameters:**  
  - `d0, d1, ..., dn` → Dimensions of the output array  
- **Description:** Generates numbers from a **standard normal distribution** (mean=0, std=1).  
- **Example Use:** Gaussian noise, statistical experiments.

---

## 🔹 5. `np.random.normal(loc=0.0, scale=1.0, size=None)`
- **Parameters:**  
  - `loc` → Mean (μ)  
  - `scale` → Standard deviation (σ)  
  - `size` → Output shape  
- **Description:** Generates numbers from a **normal distribution** with a custom mean and standard deviation.  
- **Example Use:** Stock price simulation, A/B testing, modeling continuous variables.

---

## 🔹 6. `np.random.choice(a, size=None, replace=True, p=None)`
- **Parameters:**  
  - `a` → Array or list to sample from  
  - `size` → Number of samples  
  - `replace` → Sample with or without replacement  
  - `p` → Probabilities for weighted sampling  
- **Description:** Randomly selects elements from an array, optionally weighted.  
- **Example Use:** Random selection, categorical sampling, Monte Carlo simulations.

---

## 🔹 7. `np.random.shuffle(x)`
- **Parameters:**  
  - `x` → Array to shuffle  
- **Description:** Shuffles the array **in-place**. Does not return a new array.  
- **Example Use:** Randomizing datasets or sequences.

---

## 🔹 8. `np.random.permutation(x)`
- **Parameters:**  
  - `x` → Integer or array  
- **Description:** Returns a **random permutation** of numbers or array elements without modifying the original.  
- **Example Use:** Random ordering for experiments or simulations.

---

## 🔹 9. `np.random.seed(seed)`
- **Parameters:**  
  - `seed` → Integer seed for reproducibility  
- **Description:** Ensures that random numbers generated are **repeatable across runs**.  
- **Example Use:** Debugging, reproducible experiments, teaching examples.

### Without seed:
```python
np.random.randint(1, 10, 5)
# Output might be: [3, 7, 1, 4, 9]  (changes every run)
```

### With seed:
```python
np.random.seed(42)
np.random.randint(1, 10, 5)
# Output: [7, 4, 8, 5, 7]  (same every time)
```
---

## ✅ Key Notes
- Use `randint` for **integer simulations**, `rand` and `uniform` for **continuous uniform distributions**.  
- Use `randn` and `normal` for **Gaussian/normal distributions**.  
- Use `choice`, `shuffle`, and `permutation` for **sampling and ordering**.  
- Always set `seed()` for **consistent and reproducible results**.  
- Combine these functions for practical simulations like **dice rolls, stock price modeling, A/B testing**, and **synthetic dataset generation**.


In [27]:
import numpy as np


# Set seed for reproducibility

np.random.seed(42) # it will set the output always same(pseudo randomness)

print("1. RANDOM INTEGERS (randint) - Most Common")
# Generate random integers [low, high, shape)
random_ints = np.random.randint(1, 101, 10)  # 10 numbers between 1-100
print(f"10 random integers (1-100): {random_ints}")

# 2D integer array
matrix_ints = np.random.randint(0, 10, (3, 4))
print(f"3x4 integer matrix (0-9):\n{matrix_ints}")
print("-"*50)

print("\n2. UNIFORM RANDOM NUMBERS (rand)")
# Generate uniform random numbers [0, 1)
uniform_1d = np.random.rand(5)
print(f"5 uniform numbers: {uniform_1d}")

# 2D uniform random
uniform_2d = np.random.rand(2, 3)
print(f"2x3 uniform matrix:\n{uniform_2d}")
print("-"*50)

print("\n3. CUSTOM RANGE UNIFORM (uniform)")
# Random numbers in custom range [low, high, shape)
custom_uniform = np.random.uniform(10, 20, 6)
print(f"6 numbers between 10-20: {custom_uniform}")
print("-"*50)

print("\n4. NORMAL DISTRIBUTION (randn & normal)")
# Standard normal (mean=0, std=1)
standard_normal = np.random.randn(8)
print(f"8 standard normal numbers: {standard_normal}")

# Custom normal distribution (mean, std, size)
custom_normal = np.random.normal(100, 15, 6)  # mean=100, std=15
print(f"6 custom normal (μ=100, σ=15): {custom_normal}")
print("-"*50)

print("\n5. RANDOM CHOICE (choice) - Very Useful")
# Random selection from array
fruits = ['apple', 'banana', 'cherry', 'date', 'elderberry']
random_fruits = np.random.choice(fruits, 3)
print(f"3 random fruits: {random_fruits}")

# With probabilities
weighted_choice = np.random.choice([1, 2, 3], 5, p=[0.1, 0.3, 0.6])
print(f"5 weighted choices: {weighted_choice}")
print("-"*50)


print("\n6. SHUFFLE ARRAYS (shuffle)")
# Shuffle array in-place
cards = np.array(['A', 'K', 'Q', 'J', '10', '9'])
print(f"Original cards: {cards}")
np.random.shuffle(cards)
print(f"Shuffled cards: {cards}")
print("-"*50)

print("\n7. RANDOM PERMUTATIONS (permutation)")
# Create random permutations
perm = np.random.permutation(10)  # Permutation of 0-9
print(f"Permutation of 0-9: {perm}")
print("-"*50)


print("\n🔧 MOST USED FUNCTIONS SUMMARY:")
print("1. np.random.randint()   - Random integers")
print("2. np.random.rand()      - Uniform [0,1)")
print("3. np.random.uniform()   - Custom range uniform")
print("4. np.random.randn()     - Standard normal")
print("5. np.random.choice()    - Random selection")
print("6. np.random.shuffle()   - In-place shuffling")
print("7. np.random.normal()    - Custom normal distribution")
print("8. np.random.seed()      - Reproducibility")


1. RANDOM INTEGERS (randint) - Most Common
10 random integers (1-100): [77  3 70 72 27  9 62 37 97 51]
3x4 integer matrix (0-9):
[[9 7 5 7]
 [8 3 0 0]
 [9 3 6 1]]
--------------------------------------------------

2. UNIFORM RANDOM NUMBERS (rand)
5 uniform numbers: [0.71227059 0.14808693 0.99774049 0.26678101 0.97661496]
2x3 uniform matrix:
[[0.41103701 0.03305073 0.34507125]
 [0.63435134 0.68070545 0.53093458]]
--------------------------------------------------

3. CUSTOM RANGE UNIFORM (uniform)
6 numbers between 10-20: [14.47783165 15.52893089 15.92696724 10.80853326 13.69654456 12.42159938]
--------------------------------------------------

4. NORMAL DISTRIBUTION (randn & normal)
8 standard normal numbers: [-0.137291    1.40132156 -0.04540266  0.21693673  0.51242373  0.54348869
  0.02809946 -1.19708706]
6 custom normal (μ=100, σ=15): [111.84509207 106.47234195  83.54871552  89.76547654 113.31267422
 109.08224696]
--------------------------------------------------

5. RANDOM CHOICE

# NumPy Array Creation from range

NumPy provides several functions to generate sequences of numbers efficiently. These are widely used in scientific computing, simulations, and plotting.

---

## 🔹 1. `np.arange(start, stop, step)`
- **Parameters:**  
  - `start` → Starting value of the sequence (inclusive)  
  - `stop` → End value of the sequence (exclusive)  
  - `step` → Spacing between values (default: 1)  
- **Description:** Creates an array of evenly spaced values with a specified **step size**.  
- **Example Use:** Generating indices, time steps, or simple sequences.

---

## 🔹 2. `np.linspace(start, stop, num=50, endpoint=True)`
- **Parameters:**  
  - `start` → Starting value of the sequence  
  - `stop` → Ending value of the sequence  
  - `num` → Number of samples to generate (default: 50)  
  - `endpoint` → If True, includes `stop` in the output (default: True)  
- **Description:** Creates an array of **linearly spaced values** between start and stop.  
- **Example Use:** Plotting smooth curves, interpolation, linear scaling.

---

## 🔹 3. `np.logspace(start, stop, num=50, base=10.0, endpoint=True)`
- **Parameters:**  
  - `start` → Start exponent  
  - `stop` → Stop exponent  
  - `num` → Number of values (default: 50)  
  - `base` → Base of the logarithm (default: 10.0)  
  - `endpoint` → If True, includes `stop` in the output  
- **Description:** Generates values **logarithmically spaced** between `base**start` and `base**stop`.  
- **Example Use:** Logarithmic plots, frequency scales, scientific simulations.

---
## 🔹 4. `np.geomspace(start, stop, num=50, endpoint=True)`
- **Parameters:**  
  - `start` → Starting value (>0 for positive sequences)  
  - `stop` → Ending value  
  - `num` → Number of points (default: 50)  
  - `endpoint` → If True, includes `stop` in the output  
- **Description:** Creates values **geometrically spaced**, meaning the **ratio between consecutive elements is constant**.  
- **Example Use:** Exponential growth/decay simulations, multiplicative sequences, log-scale plotting.  
- **Note:** Can generate both positive and negative sequences (negative requires an even number of points).
---


## ✅ Key Notes
- `arange()` → Step-based; may have floating-point errors.  
- `linspace()` → Count-based; guarantees a specific number of points.  
- `logspace()` → Logarithmic scaling; good for orders-of-magnitude plots.  
- `geomspace()` → Geometric spacing; ideal for sequences where ratios are constant.  
- Combine these functions with plotting libraries (e.g., Matplotlib) for **visualizing continuous, logarithmic, or multiplicative data**.

---

### 🔹 Quick Comparison Table

| Function       | Output Type           | Spacing Type      | Includes End? |
|----------------|---------------------|-----------------|---------------|
| `arange`       | Array of numbers     | Step-based       | No (exclusive)|
| `linspace`     | Array of numbers     | Linear, count-based | Optional    |
| `logspace`     | Array of numbers     | Logarithmic      | Optional      |
| `geomspace`    | Array of numbers     | Geometric ratio  | Optional      |


In [32]:
import numpy as np

print("=== NUMPY SEQUENCE CREATION FUNCTIONS ===\n")

# 1. arange
print("1. ARANGE")
arr_arange = np.arange(0, 10, 1)  # Start=0, Stop=10 (exclusive), Step=2
print(f"np.arange(0,10,2): {arr_arange}")
print("-"*50)

# 2. linspace
print("2. LINSPACE")
arr_linspace = np.linspace(1, 3, 4)  # 5 evenly spaced numbers between 0 and 1
print(f"np.linspace(1,3,4): {arr_linspace}")
print("-"*50)

# 3. logspace
print("3. LOGSPACE")
arr_logspace = np.logspace(1, 3, 4)  # 4 numbers from 10^1 to 10^3
print(f"np.logspace(1,3,4): {arr_logspace}")
print("-"*50)

# 4. geomspace
print("4. GEOMSPACE")
arr_geomspace = np.geomspace(1, 16, 5)  # 5 numbers geometrically spaced from 1 to 16
print(f"np.geomspace(1,16,5): {arr_geomspace}")
print("-"*50)

# Quick comparison table
print("=== QUICK COMPARISON ===")
print(f"arange:    {arr_arange}")
print(f"linspace:  {arr_linspace}")
print(f"logspace:  {arr_logspace}")
print(f"geomspace: {arr_geomspace}")
print("-"*50)

=== NUMPY SEQUENCE CREATION FUNCTIONS ===

1. ARANGE
np.arange(0,10,2): [0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------
2. LINSPACE
np.linspace(1,3,4): [1.         1.66666667 2.33333333 3.        ]
--------------------------------------------------
3. LOGSPACE
np.logspace(1,3,4): [  10.           46.41588834  215.443469   1000.        ]
--------------------------------------------------
4. GEOMSPACE
np.geomspace(1,16,5): [ 1.  2.  4.  8. 16.]
--------------------------------------------------
=== QUICK COMPARISON ===
arange:    [0 1 2 3 4 5 6 7 8 9]
linspace:  [1.         1.66666667 2.33333333 3.        ]
logspace:  [  10.           46.41588834  215.443469   1000.        ]
geomspace: [ 1.  2.  4.  8. 16.]
--------------------------------------------------


# Creating Matrices for Linear Algebra with NumPy

NumPy provides convenient functions to create matrices and special arrays used in linear algebra computations. These matrices are widely used in solving systems of equations, transformations, and other numerical computations.

---

## 🔹 1. `np.eye(N, M=None, k=0, dtype=float)`
- **Parameters:**  
  - `N` → Number of rows  
  - `M` → Number of columns (defaults to `N`)  
  - `k` → Diagonal offset (0=main, >0=above, <0=below)  
  - `dtype` → Data type of elements  
- **Description:** Creates an **identity matrix** (ones on the diagonal, zeros elsewhere).  

---

## 🔹 2. `np.identity(n, dtype=float)`
- **Parameters:**  
  - `n` → Number of rows and columns (square matrix)  
  - `dtype` → Data type  
- **Description:** Returns a **square identity matrix**.  
- **Note:** Similar to `eye(n)` but simpler for square matrices.

---

## 🔹 3. `np.zeros((rows, cols), dtype=float)`
- **Parameters:**  
  - `rows, cols` → Shape of the matrix  
  - `dtype` → Data type  
- **Description:** Creates a **matrix filled with zeros**.  
- **Use Case:** Placeholder matrices or initialization.

---

## 🔹 4. `np.ones((rows, cols), dtype=float)`
- **Parameters:**  
  - `rows, cols` → Shape of the matrix  
  - `dtype` → Data type  
- **Description:** Creates a **matrix filled with ones**.  
- **Use Case:** Scaling, bias matrices, or testing.

---

## 🔹 5. `np.full((rows, cols), fill_value, dtype=None)`
- **Parameters:**  
  - `rows, cols` → Shape of the matrix  
  - `fill_value` → Value to fill the matrix  
  - `dtype` → Optional data type  
- **Description:** Creates a matrix **filled with a specific value**.  

---

## 🔹 6. `np.diag(v, k=0)`
- **Parameters:**  
  - `v` → 1D array or 2D array  
  - `k` → Diagonal offset  
- **Description:**  
  - If `v` is 1D → returns a 2D matrix with `v` on the `k`-th diagonal.  
  - If `v` is 2D → extracts the `k`-th diagonal as a 1D array.  
- **Use Case:** Constructing diagonal matrices, extracting diagonals.

---

## 🔹 7. `np.random.rand(rows, cols)`
- **Parameters:**  
  - `rows, cols` → Shape of the matrix  
- **Description:** Creates a matrix with **uniform random values** in `[0,1)`.  
- **Use Case:** Random initializations, stochastic simulations.

---

## ✅ Key Notes
- Use `eye()` or `identity()` for identity matrices.  
- Use `zeros()`, `ones()`, or `full()` for general initialization.  
- Use `diag()` to create or extract diagonal matrices.  
- Random matrices are useful in simulations and testing linear algebra algorithms.  



In [33]:
import numpy as np

print("=== NUMPY MATRIX CREATION FOR LINEAR ALGEBRA ===\n")

# Set seed for reproducibility
np.random.seed(42)

print("1. IDENTITY MATRIX (np.eye)")
I3 = np.eye(3)                    # 3x3 identity
I_rect = np.eye(3, 4)             # 3x4 identity-like
I_offset = np.eye(3, k=1)         # Diagonal offset by 1
print(f"3x3 Identity:\n{I3}")
print(f"3x4 Rectangular:\n{I_rect}")
print(f"3x3 with k=1:\n{I_offset}")
print("-" * 50)

print("2. SQUARE IDENTITY (np.identity)")
I_square = np.identity(4)         # 4x4 identity
print(f"4x4 Identity:\n{I_square}")
print("-" * 50)

print("3. ZERO MATRIX (np.zeros)")
Z_2x3 = np.zeros((2, 3))          # 2x3 zeros
Z_3x3 = np.zeros((3, 3))          # 3x3 zeros
Z_int = np.zeros((2, 2), dtype=int) # Integer zeros
print(f"2x3 Zeros:\n{Z_2x3}")
print(f"3x3 Zeros:\n{Z_3x3}")
print(f"2x2 Integer Zeros:\n{Z_int}")
print("-" * 50)

print("4. ONES MATRIX (np.ones)")
O_2x2 = np.ones((2, 2))           # 2x2 ones
O_3x4 = np.ones((3, 4))           # 3x4 ones
O_float = np.ones((2, 3), dtype=np.float32) # Float32 ones
print(f"2x2 Ones:\n{O_2x2}")
print(f"3x4 Ones:\n{O_3x4}")
print(f"2x3 Float32 Ones:\n{O_float}")
print("-" * 50)

print("5. FULL MATRIX (np.full)")
F_5 = np.full((2, 3), 5)          # 2x3 filled with 5
F_pi = np.full((3, 3), np.pi)     # 3x3 filled with pi
F_str = np.full((2, 2), "X")      # 2x2 filled with "X"
print(f"2x3 filled with 5:\n{F_5}")
print(f"3x3 filled with pi:\n{F_pi}")
print(f"2x2 filled with 'X':\n{F_str}")
print("-" * 50)

print("6. DIAGONAL MATRIX (np.diag)")
# Create from 1D array
D1 = np.diag([1, 2, 3])           # 3x3 diagonal
D_offset = np.diag([1, 2], k=1)   # 3x3 with offset diagonal
print(f"3x3 Diagonal [1,2,3]:\n{D1}")
print(f"3x3 with k=1:\n{D_offset}")

# Extract diagonal from 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6], 
                   [7, 8, 9]])
main_diag = np.diag(matrix)       # Extract main diagonal
upper_diag = np.diag(matrix, k=1) # Extract upper diagonal
print(f"Matrix:\n{matrix}")
print(f"Main diagonal: {main_diag}")
print(f"Upper diagonal (k=1): {upper_diag}")
print("-" * 50)

print("7. RANDOM MATRIX (np.random.rand)")
R_2x2 = np.random.rand(2, 2)      # 2x2 random [0,1)
R_3x3 = np.random.rand(3, 3)      # 3x3 random [0,1)
print(f"2x2 Random:\n{R_2x2}")
print(f"3x3 Random:\n{R_3x3}")
print("-" * 50)


=== NUMPY MATRIX CREATION FOR LINEAR ALGEBRA ===

1. IDENTITY MATRIX (np.eye)
3x3 Identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3x4 Rectangular:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
3x3 with k=1:
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
--------------------------------------------------
2. SQUARE IDENTITY (np.identity)
4x4 Identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------------------------------------
3. ZERO MATRIX (np.zeros)
2x3 Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
3x3 Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2x2 Integer Zeros:
[[0 0]
 [0 0]]
--------------------------------------------------
4. ONES MATRIX (np.ones)
2x2 Ones:
[[1. 1.]
 [1. 1.]]
3x4 Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2x3 Float32 Ones:
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
5. FULL MATRIX (np.full)
2x3 filled with 5:
[[5 5 5]
 [5 5 5]]
3x3 filled with pi:
[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.141

# NumPy Indexing, Slicing, and Iteration

NumPy provides powerful and flexible ways to access, manipulate, and iterate over arrays. Understanding these operations is key for efficient numerical computing.

---

## 🔹 1. Basic Indexing
- Access individual elements using **square brackets**.  
- Works for **1D, 2D, and 3D arrays**: `arr[index]`, `arr[row, col]`, `arr[depth, row, col]`.  
- **Negative indexing** selects elements from the end.  
- **3D arrays** can be indexed by depth, row, and column.

---

## 🔹 2. Slicing
- Extract subarrays using `start:stop:step`.  
- **1D slicing:**  
  - `arr[start:stop]` → elements from start to stop-1  
  - `arr[:stop]` → first stop elements  
  - `arr[start:]` → elements from start to end  
  - `arr[::step]` → every step-th element  
  - `arr[::-1]` → reverse array  

- **2D slicing:**  
  - `arr[row_start:row_stop, col_start:col_stop]`  
  - Can include steps: `arr[::2, ::3]` → every 2nd row, every 3rd column  

---

## 🔹 3. Boolean Indexing
- Use boolean conditions to select elements.  
- Examples:  
  - `arr[arr > 50]` → all elements greater than 50  
  - `(arr > 30) & (arr < 70)` → elements between 30 and 70  
- Works with multi-dimensional arrays.  

---

## 🔹 4. Fancy Indexing
- Select multiple specific elements using **integer arrays**.  
- Examples:  
  - 1D → `arr[[0,2,4]]`  
  - 2D rows → `arr[[0,2]]`  
  - 2D columns → `arr[:, [1,3]]`  
  - 2D specific elements → `arr[[0,2],[1,3]]`  
- Returns a **copy**, not a view.  

---

## 🔹 5. Combined Indexing and Slicing
- Combine slicing, boolean masks, and fancy indexing.  
- Examples:  
  - Submatrix and specific columns: `arr[:2, [0,3]]`  
  - Boolean mask on a slice: `arr[:3][arr[:3] > 5]`  

---

## 🔹 6. Views vs Copies
- **Slicing** → creates **view** (modifying it affects the original).  
- **Fancy/Boolean indexing** → creates **copy** (original array unchanged).  

---

## 🔹 7. 3D Array Indexing
- Access slices along different axes:  
  - `arr[0]` → first 2D slice  
  - `arr[:, 1]` → second row of all slices  
  - `arr[:, :, 2]` → third column of all slices  

---

## 🔹 8. Iterating Arrays with `np.nditer()`
- **Efficient multi-dimensional iteration**.  
- Features:  
  - Row-major iteration (default)  
  - Column-major iteration (`order='F'`)  
  - Access indices via `flags=['multi_index']`  
  - Modify elements during iteration (`op_flags=['readwrite']`)  
  - External loop for large arrays (`flags=['external_loop']`)  
  - Iteration with different data types  

---

## ✅ Key Notes
- Indexing and slicing are **fast and memory-efficient**.  
- Fancy and boolean indexing create **copies**.  
- `np.nditer()` allows **efficient iteration** with control over memory order, modification, and chunked access.  
- These tools work seamlessly for **1D, 2D, and higher-dimensional arrays**.


In [35]:
import numpy as np

print("=== NUMPY INDEXING AND SLICING DEMONSTRATION ===\n")

# Create sample arrays
np.random.seed(42)
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
arr_3d = np.random.randint(1, 50, (3, 4, 5))

print("ORIGINAL ARRAYS:")
print(f"1D Array: {arr_1d}")
print(f"2D Array:\n{arr_2d}")
print(f"3D Array shape: {arr_3d.shape}")
print("-" * 50)

print("1. BASIC INDEXING")
print(f"1D - arr_1d[3]: {arr_1d[3]}")                    # Single element
print(f"1D - arr_1d[-1]: {arr_1d[-1]}")                  # Last element
print(f"2D - arr_2d[1, 2]: {arr_2d[1, 2]}")             # Row 1, Col 2
print(f"2D - arr_2d[2][3]: {arr_2d[2][3]}")             # Alternative syntax
print(f"3D - arr_3d[0, 1, 2]: {arr_3d[0, 1, 2]}")       # 3D indexing
print("-" * 50)

print("2. SLICING - 1D ARRAY")
print(f"arr_1d[2:6]: {arr_1d[2:6]}")                    # From index 2 to 5
print(f"arr_1d[:4]: {arr_1d[:4]}")                      # First 4 elements
print(f"arr_1d[5:]: {arr_1d[5:]}")                      # From index 5 to end
print(f"arr_1d[::2]: {arr_1d[::2]}")                    # Every 2nd element
print(f"arr_1d[1::2]: {arr_1d[1::2]}")                  # Every 2nd, starting from 1
print(f"arr_1d[::-1]: {arr_1d[::-1]}")                  # Reverse array
print("-" * 50)

print("3. MULTI-DIMENSIONAL SLICING - 2D ARRAY")
print(f"First 2 rows:\n{arr_2d[:2]}")
print(f"Rows 1 to 3:\n{arr_2d[1:3]}")
print(f"First 2 columns:\n{arr_2d[:, :2]}")
print(f"Columns 1 to 3:\n{arr_2d[:, 1:3]}")
print(f"Sub-matrix (rows 1-2, cols 2-3):\n{arr_2d[1:3, 2:4]}")
print(f"Every 2nd row:\n{arr_2d[::2]}")
print(f"Every 2nd column:\n{arr_2d[:, ::2]}")
print(f"Every 2nd row and column:\n{arr_2d[::2, ::2]}")
print("-" * 50)

print("4. BOOLEAN INDEXING")
# Create boolean masks
mask_1d = arr_1d > 50
mask_2d = arr_2d > 7

print(f"1D Array: {arr_1d}")
print(f"Mask (arr_1d > 50): {mask_1d}")
print(f"Elements > 50: {arr_1d[arr_1d > 50]}")
print(f"Elements between 30 and 70: {arr_1d[(arr_1d > 30) & (arr_1d < 70)]}")
print(f"Even numbers: {arr_1d[arr_1d % 20 == 0]}")

print(f"\n2D Array:\n{arr_2d}")
print(f"Elements > 7: {arr_2d[arr_2d > 7]}")
print(f"Even numbers in 2D: {arr_2d[arr_2d % 2 == 0]}")
print("-" * 50)

print("5. FANCY INDEXING")
# Integer array indexing
indices_1d = [0, 2, 4, 6]
indices_2d_rows = [0, 2]
indices_2d_cols = [1, 3]

print(f"1D - indices [0, 2, 4, 6]: {arr_1d[[0, 2, 4, 6]]}")
print(f"2D - rows [0, 2]:\n{arr_2d[[0, 2]]}")
print(f"2D - columns [1, 3]:\n{arr_2d[:, [1, 3]]}")
print(f"2D - specific elements [0,2] & [1,3]: {arr_2d[[0, 2], [1, 3]]}")

# More complex fancy indexing
row_indices = [0, 1, 2]
col_indices = [1, 2, 3]
print(f"2D - diagonal elements: {arr_2d[row_indices, col_indices]}")
print("-" * 50)

print("6. COMBINED INDEXING AND SLICING")
print(f"2D - First 2 rows, last 2 columns:\n{arr_2d[:2, -2:]}")
print(f"2D - Every 2nd row, specific columns [0, 3]:\n{arr_2d[::2, [0, 3]]}")
print(f"2D - Boolean mask on sliced array (>5 in first 3 rows):\n{arr_2d[:3][arr_2d[:3] > 5]}")
print("-" * 50)

print("7. VIEWS VS COPIES DEMONSTRATION")
print("Slicing creates VIEWS (modifies original):")
arr_slice = arr_1d[2:6]  # This is a view
print(f"Original: {arr_1d}")
arr_slice[0] = 999
print(f"After modifying slice: {arr_1d}")

print("\nFancy indexing creates COPIES (doesn't modify original):")
arr_copy = arr_1d[[1, 3, 5]]  # This is a copy
arr_copy[0] = 111
print(f"After modifying copy: {arr_1d} (original unchanged)")
print("-" * 50)

print("8. PRACTICAL EXAMPLES")


print("9. 3D ARRAY INDEXING")
print(f"3D Array shape: {arr_3d.shape}")
print(f"First 2D slice:\n{arr_3d[0]}")
print(f"Second row of all 2D slices:\n{arr_3d[:, 1]}")
print(f"Third column of all 2D slices:\n{arr_3d[:, :, 2]}")
print("-" * 50)

print("10. np.nditer() - EFFICIENT ARRAY ITERATION")
print("Basic iteration:")
print("1D Array iteration:")
for x in np.nditer(arr_1d):
    print(x, end=' ')
print("\n")

print("2D Array iteration (row-major order):")
for x in np.nditer(arr_2d):
    print(x, end=' ')
print("\n")

print("2D Array iteration with indices:")
it = np.nditer(arr_2d, flags=['multi_index'])
while not it.finished:
    print(f"Value: {it[0]}, Index: {it.multi_index}", end=' | ')
    it.iternext()
print("\n")

print("Column-major (Fortran) order:")
for x in np.nditer(arr_2d, order='F'):
    print(x, end=' ')
print("\n")

print("Modifying array during iteration (readwrite mode):")
arr_modifiable = np.array([[1, 2], [3, 4]])
print(f"Original: {arr_modifiable.flatten()}")
with np.nditer(arr_modifiable, op_flags=['readwrite']) as it:
    for x in it:
        x[...] = x * 2  # Double each element
print(f"After modification: {arr_modifiable.flatten()}")

print("\nExternal loop (faster for large arrays):")
print("Values in external loop:", end=' ')
for x in np.nditer(arr_2d, flags=['external_loop']):
    print(x, end=' ')
print("\n")

print("Iterating with different data types:")
for x in np.nditer(arr_2d, op_flags=['readonly'], order='F', flags=['external_loop']):
    print(f"Chunk: {x}")
print("-" * 50)

print("=== ALL INDEXING AND ITERATION METHODS DEMONSTRATED ===")

=== NUMPY INDEXING AND SLICING DEMONSTRATION ===

ORIGINAL ARRAYS:
1D Array: [ 10  20  30  40  50  60  70  80  90 100]
2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
3D Array shape: (3, 4, 5)
--------------------------------------------------
1. BASIC INDEXING
1D - arr_1d[3]: 40
1D - arr_1d[-1]: 100
2D - arr_2d[1, 2]: 7
2D - arr_2d[2][3]: 12
3D - arr_3d[0, 1, 2]: 19
--------------------------------------------------
2. SLICING - 1D ARRAY
arr_1d[2:6]: [30 40 50 60]
arr_1d[:4]: [10 20 30 40]
arr_1d[5:]: [ 60  70  80  90 100]
arr_1d[::2]: [10 30 50 70 90]
arr_1d[1::2]: [ 20  40  60  80 100]
arr_1d[::-1]: [100  90  80  70  60  50  40  30  20  10]
--------------------------------------------------
3. MULTI-DIMENSIONAL SLICING - 2D ARRAY
First 2 rows:
[[1 2 3 4]
 [5 6 7 8]]
Rows 1 to 3:
[[ 5  6  7  8]
 [ 9 10 11 12]]
First 2 columns:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Columns 1 to 3:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
Sub-matrix (rows 1-2, cols 2-3):
[[ 7  8]
 [11

In [42]:
arr = np.array([1,2,3,4,5])
arr[1:4] = 0
print(arr)

[1 0 0 0 5]
